version: '3'

services:
  postgres:
    image: 'postgres:10'
    container_name: 'postgres'
    environment:
      - 'POSTGRES_USER=admin'
      - 'POSTGRES_PASSWORD=admin'
      - 'POSTGRES_DB=licenseservices'


  licenseservice:
    build: ./License Service
    container_name: 'app-licenseservice'
    ports:
      - 8080:8080
  configurationserver:
    build: ./Configuration Server/
    container_name: 'app-config'
    ports:
      - 8180:8180
